### ISSUE TITLE
"arena list" status not same as "arena get" status.

### ISSUE THREAD

**Issue by soolaugust** [kubeflow/arena#104]
Hi,

When I create a training job using arena, I found the status of job in 'arena list' is not same as 'arena get':

![image](https://user-images.githubusercontent.com/10558124/51027228-44e65180-15cb-11e9-8c71-1db83e174f7d.png)

The command is as follow:

```bash
arena submit tf \
             --name=tf-git \
             --image=test:1.0 \
             --syncMode=git \
             --syncSource=https://github.com/chenyu85/Distribute_MNIST.git \
             "python code/Distribute_MNIST/distributed.py --job_name=ps --task_index=0 --data_dir /MNIST_data"
```

> test:1.0 is build by myself, based on _**tensorflow/tensorflow:1.5.0-devel-gpu**_ with a data file.

And the error things is that logviewer shows nothing with any job:

![image](https://user-images.githubusercontent.com/10558124/51027482-f4bbbf00-15cb-11e9-9911-33c6c9bb9c2c.png)
> the first time I use logview, it will show tfjob even if it is failed.

Could anyone help me? thanks.

**Comment by cheyang** [comment]
`arena get` shows every instance(pod)'s status inside tfjob not overall tfjob's status.  They are not the same.

You can check tfjob's status by using
```
kubectl get tfjob -l release=tf-git -o=yaml
```
Please pay attention to status section of the result.

You can check the pod status inside tfjob by using

```
kubectl get po -l tf_job_name=tf-git-tfjob
```

**Comment by cheyang** [comment]
And you can check tf-operator's and the pod's log to investigate why this tfjob is pending.

**Comment by soolaugust** [comment]
@cheyang  Thanks for response,

Here are results of my tfjob:

```bash
kubectl get tfjob -l release=tf-git -o=yaml
```
![image](https://user-images.githubusercontent.com/10558124/51092459-8d239080-17d2-11e9-970e-e3ee040efe06.png)

```bash
kubectl get po -l tf_job_name=tf-git-tfjob
```
![image](https://user-images.githubusercontent.com/10558124/51092464-a3315100-17d2-11e9-9435-d9c9cf472f14.png)

```bash
kubectl logs tf-job-operator-v1alpha2-98bfbfc4-2zlkr -n arena-system
```
![image](https://user-images.githubusercontent.com/10558124/51092478-cbb94b00-17d2-11e9-9215-e9f2645fc02b.png)

**From logs of tf-job-operator, seems that serviceaccount 'arena-sytem:tf-job-operator' has no permission, right?**

**Comment by soolaugust** [comment]
I try to bind cluster admin role, but still not work.

```bash
kubectl create clusterrolebinding tf-job-operator-cluster-admin-binding --clusterrole=cluster-admin --user=system:serviceaccount:arena-system:tf-job-operator
```

**Comment by soolaugust** [comment]
After restart tf-job-operator, the log came with following message:

![image](https://user-images.githubusercontent.com/10558124/51095119-59a22f80-17ed-11e9-9157-440a09a858a7.png)

**Comment by soolaugust** [comment]
I fix this by re-create tf-operator. thanks : )
