### ISSUE TITLE
How to set dshm size for training?

### ISSUE THREAD

**Issue by Andrew-Su-0718** [kubeflow/arena#1044]
When I submit a pytorchjob with arena, I could't find parameters related to shared memory size, which is very important for pytorch training.

The size is fixed to 2Gi.
```
...
    - mountPath: /dev/shm
      name: dshm
...
...
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: dshm
...
``` 

Can anyone know how to set dshm size?

**Comment by Andrew-Su-0718** [comment]
> When I submit a pytorchjob with arena, I could't find parameters related to shared memory size, which is very important for pytorch training.
> 
> The size is fixed to 2Gi.
> 
> ```
> ...
>     - mountPath: /dev/shm
>       name: dshm
> ...
> ...
>   - emptyDir:
>       medium: Memory
>       sizeLimit: 2Gi
>     name: dshm
> ...
> ```
> 
> Can anyone know how to set dshm size?

OK. I find a workaround solution.
Modified file /charts/pytorchjob/values.yaml :
```
shmSize: 2Gi
```
to
```
shmSize: 64Gi # or any value you want
```

**Comment by yanshui177** [comment]
Same issue
