### ISSUE TITLE
arena top job lost resource information

### ISSUE THREAD

**Issue by kangzemin** [kubeflow/arena#1082]
arena top job lost resourece information
![image](https://github.com/kubeflow/arena/assets/40269690/54018c7e-2bf0-4c68-897c-94655d89c21d)

arena: v0.9.14
  BuildDate: 2024-04-10T12:54:22Z
  GitCommit: adb43b8d7490adc613f3d0762ffe9a8ee9f10552
  GitTreeState: clean
  GitTag: v0.9.14
  GoVersion: go1.20.12
  Compiler: gc
  Platform: linux/amd64

**Comment by kangzemin** [comment]
Thank you for your guidance!
When I deploy exporter with https://github.com/kubeflow/arena/blob/master/docs/top/prometheus.md, there has been an error:
![image](https://github.com/kubeflow/arena/assets/40269690/05141af7-49c9-45a2-a190-f5b39945785e)
so I fix kubernetes-artifacts/prometheus/gpu-exporter.yaml,and delete line 26and30(type: FileOrCreate)
now pod is running.

But exporter pod log is:
```
time="2024-05-11T03:28:50Z" level=info msg="runtime is docker"
{"level":"error","msg":"GetDriverVersion(): 535.161.07","time":"2024-05-11T03:28:50Z"}
```
Is there something wrong?

kubernests version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.25.4-1", GitCommit:"f23e643ebd790a62a54b376116d094a732f28263", GitTreeState:"archive", BuildDate:"2023-02-02T00:35:13Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.25.4-1", GitCommit:"f23e643ebd790a62a54b376116d094a732f28263", GitTreeState:"archive", BuildDate:"2023-02-01T01:11:45Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
_attention: my kubernetes runtime is containerd._
nvidia-smi:
```
 NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2
```

**Comment by kangzemin** [comment]
> Thank you for your guidance! When I deploy exporter with https://github.com/kubeflow/arena/blob/master/docs/top/prometheus.md, there has been an error: ![image](https://private-user-images.githubusercontent.com/40269690/329750989-05141af7-49c9-45a2-a190-f5b39945785e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk5MDMsIm5iZiI6MTcxNTM5OTYwMywicGF0aCI6Ii80MDI2OTY5MC8zMjk3NTA5ODktMDUxNDFhZjctNDljOS00NWEyLWExOTAtZjViMzk5NDU3ODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzNTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMzM2ZDg5YTMwYmQ5NzdiY2MwYzVhNGVmZDU1YTcwNzQyOWE3NzA3OWU0N2VkMTkxYzRiMmU3Nzg1YTA4MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MqePMdae4mkENCm4i1Kgy9S7Vg1w3DumGwSy1EjKCoo) so I fix kubernetes-artifacts/prometheus/gpu-exporter.yaml,and delete line 26and30(type: FileOrCreate) now pod is running.
> 
> But exporter pod log is:
> 
> ```
> time="2024-05-11T03:28:50Z" level=info msg="runtime is docker"
> {"level":"error","msg":"GetDriverVersion(): 535.161.07","time":"2024-05-11T03:28:50Z"}
> ```
> 
> Is there something wrong?
> 
> kubernests version:
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.25.4-1", GitCommit:"f23e643ebd790a62a54b376116d094a732f28263", GitTreeState:"archive", BuildDate:"2023-02-02T00:35:13Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
> Kustomize Version: v4.5.7
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.25.4-1", GitCommit:"f23e643ebd790a62a54b376116d094a732f28263", GitTreeState:"archive", BuildDate:"2023-02-01T01:11:45Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> _attention: my kubernetes runtime is containerd._ nvidia-smi:
> 
> ```
>  NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2
> ```

@Syulin7

**Comment by Syulin7** [comment]
> so I fix kubernetes-artifacts/prometheus/gpu-exporter.yaml,and delete line 26and30(type: FileOrCreate)

@kangzemin You need to mount the node's containerd.sock to /run/containerd/containerd.sock inside the container.

**Comment by kangzemin** [comment]
> > so I fix kubernetes-artifacts/prometheus/gpu-exporter.yaml,and delete line 26and30(type: FileOrCreate)
> 
> @kangzemin You need to mount the node's containerd.sock to /run/containerd/containerd.sock inside the container.

@Syulin7 ok,I mount nodes‘s /run/containerd/containerd.sock to /run/containerd/containerd.sock inside the container. and exporter pod is running.


but exporter pod log is error:

```
time="2024-05-14T06:36:07Z" level=info msg="runtime is containerd"
{"level":"error","msg":"GetDriverVersion(): 535.161.07","time":"2024-05-14T06:36:07Z"}
```
 query from prometheus is empty:
```
kubectl get --raw '/api/v1/namespaces/arena-system/services/prometheus-svc:prometheus/proxy/api/v1/query?query=nvidia_gpu_num_devices' 
{"status":"success","data":{"resultType":"vector","result":[]}}
```
![gpu-exporter](https://github.com/kubeflow/arena/assets/40269690/2798c41b-3587-4c74-a971-3c06711a0a7d)

**Comment by Syulin7** [comment]
@kangzemin  Execute the following command to check if node-gpu-exporter exposes metrics.
```
kubectl get --raw '/api/v1/namespaces/arena-system/services/node-gpu-exporter:http-metrics/proxy/'
```

**Comment by kangzemin** [comment]
> @kangzemin Execute the following command to check if node-gpu-exporter exposes metrics.
> 
> ```
> kubectl get --raw '/api/v1/namespaces/arena-system/services/node-gpu-exporter:http-metrics/proxy/'
> ```
This is result :
![image](https://github.com/kubeflow/arena/assets/40269690/90d682de-26cc-448c-b982-5ef25f315422)

![image](https://github.com/kubeflow/arena/assets/40269690/9388b2eb-09c5-44c5-859c-779ce1d46e98)

![image](https://github.com/kubeflow/arena/assets/40269690/23e635e0-c5cb-4b34-ac6b-ebb150f2152c)

**Comment by kangzemin** [comment]
> > @kangzemin Execute the following command to check if node-gpu-exporter exposes metrics.
> > ```
> > kubectl get --raw '/api/v1/namespaces/arena-system/services/node-gpu-exporter:http-metrics/proxy/'
> > ```
> 
> This is result : ![image](https://private-user-images.githubusercontent.com/40269690/330651402-90d682de-26cc-448c-b982-5ef25f315422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDQzNDcsIm5iZiI6MTcxNTc0NDA0NywicGF0aCI6Ii80MDI2OTY5MC8zMzA2NTE0MDItOTBkNjgyZGUtMjZjYy00NDhjLWI5ODItNWVmMjVmMzE1NDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNmJjYTJmNGE4YjlmMDRkNjlhYmRmMTQyNzk0NTgwMzBiNzIwMGIwMDdhYTU0NGJhYzkyYjEwMGJkMDEwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uGgR7s-MKP7RnaseWK0CrXgKUOTmhOCVgOZBYY2003Y)
> 
> ![image](https://private-user-images.githubusercontent.com/40269690/330651316-9388b2eb-09c5-44c5-859c-779ce1d46e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDQzNDcsIm5iZiI6MTcxNTc0NDA0NywicGF0aCI6Ii80MDI2OTY5MC8zMzA2NTEzMTYtOTM4OGIyZWItMDljNS00NGM1LTg1OWMtNzc5Y2UxZDQ2ZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYWRkNDRhYzZjMWZkOGQ5ZjFkM2FkZjBlZmIwNGRiYThmNDNlOWYzNmE5ZjRhYjc0ZDdiNTIwMWE3MjE0ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IgXOHFSLsqKN9IDNAJQiatweLSyt0Li8_lUdEM_FkB8)
> 
> ![image](https://private-user-images.githubusercontent.com/40269690/330651645-23e635e0-c5cb-4b34-ac6b-ebb150f2152c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDQzNDcsIm5iZiI6MTcxNTc0NDA0NywicGF0aCI6Ii80MDI2OTY5MC8zMzA2NTE2NDUtMjNlNjM1ZTAtYzVjYi00YjM0LWFjNmItZWJiMTUwZjIxNTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NzNmNDgyYjI3ZjBjZWRkMmI2OTA2NTI0OWYzNjFkYmE4ZWU0MDA0NjVmMzk0MTRiNWQwMTZhOWQ3YjZiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.geecPLQYqYjF8PZ4yKOdk_oQF41P4YR3Jg7SipPs3JM)

@Syulin7

**Comment by Syulin7** [comment]
https://github.com/kubeflow/arena/pull/1087

@kangzemin I submitted a PR to fix this issue. Please refer to this PR to redeploy the service.

**Comment by kangzemin** [comment]
> The Prometheus deployed here is for testing only. In a production environment, you should deploy your own Prometheus service and ensure data persistence.
@Syulin7  Ok，Thank you ！

**Comment by Syulin7** [comment]
@kangzemin  Does it work after trying again? Are there any other issues?

**Comment by kangzemin** [comment]
> @kangzemin Does it work after trying again? Are there any other issues?

The problem still exists。
![image](https://github.com/kubeflow/arena/assets/40269690/5a8c51a3-9337-4007-acab-2b09c718ebff)
But prometheus looks normal
```
kubectl get --raw '/api/v1/namespaces/arena-system/services/node-gpu-exporter:http-metrics/proxy/'
```
![prometheus](https://github.com/kubeflow/arena/assets/40269690/0f516f43-d7bf-4b6d-a467-a094cea966d8)

grafana only  gpunode dashboard has data, other is empty.

Can you give me some advice?

**Comment by Syulin7** [comment]
@kangzemin  It seems that the metrics collected by node-gpu-exporter do not include the pod_name. Have you updated the node-gpu-exporter image and modified the resource limit value according to https://github.com/kubeflow/arena/pull/1087?

**Comment by kangzemin** [comment]
It seems that the metrics collected by node-gpu-exporter do not include the pod_name. Have you updated the node-gpu-exporter image and modified the resource limit value according to #1087?

@Syulin7 Yes, I fix deployment, use image:gpu-prometheus-exporter:v1.0.1-b2c2f9b. and  limit cpu 1, mem 2000Mi.
arena top job, about gpu info is N/A .
