### ISSUE TITLE
Which framework does arena support

### ISSUE THREAD

**Issue by Eric-Zhang1990** [kubeflow/arena#112]
@willb @ewilderj  @aronchick  @mhausenblas   Can someone tell me which framework arena can support  and give some examples for each framework?
Thanks very much.

**Comment by Eric-Zhang1990** [comment]
@carmark  Thank you for your reply.  Can you give me some examples of pytorch or caffe training using multi GPUs from master and node on kubernets?  Thanks.

**Comment by xieydd** [comment]
@Eric-Zhang1990 You can see the example of horovod pytorch : https://github.com/uber/horovod/blob/master/examples/pytorch_imagenet_resnet50.py

**Comment by wsxiaozhang** [comment]
if more queries come, pls reopen
