### ISSUE TITLE
Status is running, but cannot get nvidia info

### ISSUE THREAD

**Issue by Eric-Zhang1990** [kubeflow/arena#114]
@cheyang  I reboot the system and run the tf-job, now it is running, but it is always in status running and I can not get any output infomation about the use of gpu, like this:
![_ _20190125173713](https://user-images.githubusercontent.com/24602893/51737670-2488bd80-20c8-11e9-96f2-66a8ffc44da5.png)
------------
![_ _20190125173909](https://user-images.githubusercontent.com/24602893/51737685-2bafcb80-20c8-11e9-90de-6f121c21106d.png)
------------
On the web, I can see the tf-job is running (and status is always on running), but can not get the log info.
![_ _20190125173952](https://user-images.githubusercontent.com/24602893/51737753-526e0200-20c8-11e9-9f7d-5f4ef48a2bfc.png)

**Comment by cheyang** [comment]
You can check by using `arena logs tf-git`. Personally, I suspect it's caused by network issue. It's something similar to https://github.com/kubeflow/arena/issues/102.
