### ISSUE TITLE
manifest for registry.cn-zhangjiakou.aliyuncs.com/acs/et-operator:v0.1.5-aliyun-d298c36 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by xiyu1sun20230911** [kubeflow/arena#1168]
### What happened?

I tried installing Arena v0.10.0 by downloading the release version and running the install.sh script. It showed "Arena has been installed successfully!" However, when I checked the namespace where Arena was installed, there was an ImagePullBackOff issue. The image registry.cn-zhangjiakou.aliyuncs.com/acs/et-operator:v0.1.5-aliyun-d298c36 cannot be pulled. Please update the image tag or provide an accessible image.

### What did you expect to happen?

All the image could be pull.

### Environment

Kubernetes version:

```bash
$ kubectl version

```

Arena version:
v0.10.0
```bash
$ arena version
arena: v0.10.0+62ed8b9
  BuildDate: 2024-09-29T13:52:48Z
  GitCommit: 62ed8b98a8c2edd6196e3b885d07b525e24e0c2d
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: linux/amd64
```

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by ChenYi015** [comment]
@xiyu1sun20230911 Thanks for reporting the issue, we have fixed it and will release the bugfix in `v0.10.2` ASAP.
