### ISSUE TITLE
when should I set hostIPC to false?

### ISSUE THREAD

**Issue by asdfsx** [kubeflow/arena#125]
https://github.com/kubeflow/arena/blob/25b7c75624bcdbb6609449722f2407db087cf795/charts/tfjob/values.yaml#L5-L9

I start a service in container, and try to connect to this service using `localhost:xxxx`, it always failed.

But after I set `useHostIPC` to `false`, I can connect the service using `localhost:xxxx`.

I wanna know when should I using `useHostIPC`? And if I set `HostIPC` to `false`, does it affect to the tfjob?

**Comment by cheyang** [comment]
I think you can set `useHostIPC` to false.  We set it to true because it's a simple way to increase shm size in Kubernetes. Some cases use shm for multiprocessing.

**Comment by asdfsx** [comment]
Then what about `useHostPID`. Can I set it to `false`?

**Comment by cheyang** [comment]
Yes, you can set it to false too. The impact is that `nvidia-smi` can't find the process id. inside the container.

**Comment by asdfsx** [comment]
Thx for reply！I'll close the issue!
