### ISSUE TITLE
gitlab:could not lock config file //.gitconfig: Permission denied

### ISSUE THREAD

**Issue by Chaos-Ju** [kubeflow/arena#134]
when i use gitlab in tfjob ,occur a err:

ERROR: can't create .netrc file: error setting up git credentials exit status 255: error: could not lock config file //.gitconfig: Permission denied

**Comment by Chaos-Ju** [comment]
git-sync issue link : https://github.com/kubernetes/git-sync/issues/91

**Comment by Chaos-Ju** [comment]
test the git-sync latest version:v3.1.1, fix the problem

**Comment by cheyang** [comment]
Are you using `k8s.gcr.io/git-sync:v3.1.1`? Thank you!

**Comment by Chaos-Ju** [comment]
> Are you using `k8s.gcr.io/git-sync:v3.1.1`? Thank you!

yes

**Comment by cheyang** [comment]
@Chaos-Ju , Will you fix this issue? Thanks.

**Comment by posix4e** [comment]
Let's close this out. It's stale
