### ISSUE TITLE
arena delete tfjobs error

### ISSUE THREAD

**Issue by Chaos-Ju** [kubeflow/arena#136]
delete command and logs：

[chaochchao1]$ arena delete tf-estimator1
ERRO[0000] Failed to delete tf-estimator1, the reason is that There is no training job found with the name tf-estimator1, please check it with `arena list | grep tf-estimator1`

[chaochao1]$ arena delete tf-estimator2
WARN[0000] Failed to UninstallAppsWithAppInfoFile due to exit status 123
WARN[0000] manually delete the following resource:
service "tf-estimator2-tensorboard" deleted
deployment.extensions "tf-estimator2-tensorboard" deleted
configmap "tf-estimator2-tfjob" deleted
INFO[0001] The Job tf-estimator2 has been deleted successfully
[chaochao1]$ arena list
NAME           STATUS     TRAINER  AGE  NODE
tf-estimator1  FAILED     TFJOB    0s   N/A
tf-estimator2  SUCCEEDED  TFJOB    18m  N/A
tf-estimator   SUCCEEDED  TFJOB    28m  N/A
[chaochao1]$ arena delete tf-estimator2
ERRO[0000] Failed to delete tf-estimator2, the reason is that There is no training job found with the name tf-estimator2, please check it with `arena list | grep tf-estimator2`

[chaochao1]$ arena list
NAME           STATUS     TRAINER  AGE  NODE
tf-estimator1  FAILED     TFJOB    0s   N/A
tf-estimator2  SUCCEEDED  TFJOB    18m  N/A
tf-estimator   SUCCEEDED  TFJOB    28m  N/A
[chaochao1]$ arena delete tf-estimator
WARN[0000] Failed to UninstallAppsWithAppInfoFile due to exit status 123
WARN[0000] manually delete the following resource:
service "tf-estimator-tensorboard" deleted
deployment.extensions "tf-estimator-tensorboard" deleted
configmap "tf-estimator-tfjob" deleted
INFO[0001] The Job tf-estimator has been deleted successfully
[chaochao1]$ arena list
NAME           STATUS     TRAINER  AGE  NODE
tf-estimator1  FAILED     TFJOB    0s   N/A
tf-estimator2  SUCCEEDED  TFJOB    18m  N/A
tf-estimator   SUCCEEDED  TFJOB    28m  N/A
[chaochao1]$ arena delete tf-estimator
ERRO[0000] Failed to delete tf-estimator, the reason is that There is no training job found with the name tf-estimator, please check it with `arena list | grep tf-estimator`

[chaochao1]$ arena delete tf-estimator
ERRO[0000] Failed to delete tf-estimator, the reason is that There is no training job found with the name tf-estimator, please check it with `arena list | grep tf-estimator`

**Comment by Chaos-Ju** [comment]
the reason is : should bind the clusterrole to the user/group   ,apiGroups: kubeflow.org  ,resources: tfjobs, verbs: delete 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfjob-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete

**Comment by Chaos-Ju** [comment]
In addtion ,when execute" cat /tmp/tf-chaochao2-tfjob558960642 | xargs kubectl delete --namespace test"
I think should mark the real error("Error from server (Forbidden): tfjobs.kubeflow.org "tf-chaochao2" is forbidden: User "chaochao1" cannot delete resource "tfjobs" in API group "kubeflow.org" in the namespace "test") ,not just return a error code (failed to UninstallAppsWithAppInfoFile due to exit status 123)

**Comment by cheyang** [comment]
I think the issue you'd like to report is the error message misleads you. Right?
