### ISSUE TITLE
Update k8s.io/apimachinery

### ISSUE THREAD

**Issue by ringtail** [kubeflow/arena#151]
Pls update`k8s.io/apimachinery`. New CRD operator needs to invoke runtime.Must(AddToSchem()) which is missing in current version of `k8s.io/apimachinery`.

link: 
https://github.com/kubernetes/apimachinery/blob/release-1.11/pkg/util/runtime/runtime.go#L169
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/client/clientset/versioned/scheme/register.go#L59

**Comment by cheyang** [comment]
Done
