### ISSUE TITLE
create tf-operator failed

### ISSUE THREAD

**Issue by ldd91** [kubeflow/arena#152]
when I created tf-operator uesd kubectl create -f arena/kubernetes-artifacts/tf-operator/tf-operator.yaml it failed,the log shows:
starting container process cause "exec: \opt/kubeflow/tf-operator.v2 \" : stat:/opt/kubeflow/tf-operator.v2: no such file or directory

**Comment by cheyang** [comment]
Are you using the docker image `registry.cn-zhangjiakou.aliyuncs.com/kubeflow-images-public/tf_operator:v20180621-38b886a0` ? I'm not able to reproduce it in my side.
