### ISSUE TITLE
evaluator need Replicas parameter

### ISSUE THREAD

**Issue by asdfsx** [kubeflow/arena#158]
When create a tfjob that have `evaluator`, tf-operator will check `Replicas` parameter of `evaluator`. If `Replicas` doesn't exist, it will cause runtime problem. And the tf-operator will crashed.   
Right now the tfjob.yaml doesn't have such parameter.

https://github.com/kubeflow/arena/blob/f3a359432873ef871356a0bb2153249ee0e84ed9/charts/tfjob/templates/tfjob.yaml#L728-L730

And following is the validation code in `tf-operator`

https://github.com/kubeflow/tf-operator/blob/3bf0ac83924aeea57df3e7c50bc82fc3f5546844/pkg/apis/tensorflow/validation/validation.go#L95-L97

**Comment by cheyang** [comment]
@asdfsx , would you like to help on this? Thanks.

**Comment by asdfsx** [comment]
@cheyang fix the issue by pr #257
