### ISSUE TITLE
stat /charts/tfjob: no such file or directory

### ISSUE THREAD

**Issue by Tilyp** [kubeflow/arena#161]
当我执行以下命令时 
arena submit tf              
        --name=tf-git              
        --gpus=0              
        --image=tensorflow/tensorflow:1.5.0-devel-gpu              
        --syncMode=git              
        --syncSource=https://github.com/cheyang/tensorflow-sample-code.git              
        "python code/tensorflow-sample-code/tfjob/docker/mnist/main.py --max_steps 10000"
Flag --syncMode has been deprecated, please use --sync-mode instead
Flag --syncSource has been deprecated, please use --sync-source instead
stat /charts/tfjob: no such file or directory
这个问题是什么原因

**Comment by yeya24** [comment]
When submitting a training job with arena cli, arena will try to get the job chart.
Move /arena/charts   to  $HOME or /  can solve this problem

**Comment by posix4e** [comment]
We should close this but maybe add it to faq

**Comment by Tilyp** [comment]
ok





在 Alex Newman <notifications@github.com>，2019年5月19日 03:32写道：We should close this but maybe add it to faq

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kubeflow/arena/issues/161?email_source=notifications\u0026email_token=AFUQK3JU7XQPLGTTFDLTSRDPWBKVBA5CNFSM4HLYMR5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWUTFY#issuecomment-493701527",
"url": "https://github.com/kubeflow/arena/issues/161?email_source=notifications\u0026email_token=AFUQK3JU7XQPLGTTFDLTSRDPWBKVBA5CNFSM4HLYMR5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWUTFY#issuecomment-493701527",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Tilyp** [comment]
How to deal with this problem
  The output is error: unable to recognize "/tmp/tf-git.yaml870534675": no matches for kind "TFJob" in version "kubeflow.org/v1alpha2"
  
  
  ------------------ 原始邮件 ------------------发件人：yeya24 "notifications@github.com"时　间：2019/05/18 10:55:26 星期六收件人：kubeflowarena "arena@noreply.github.com"抄送人：Tilyp "13661944195@189.cn", Author "author@noreply.github.com"主　题：Re: [kubeflow/arena] stat /charts/tfjob: no such file or directory (#161)
  When submitting a training job with arena cli, arena will try to get the job chart. Move /arena/charts to $HOME or / can solve this problem
