### ISSUE TITLE
update TFJob version to v1 or v1beta2

### ISSUE THREAD

**Issue by yeya24** [kubeflow/arena#163]
Recently tf_operator has updated TFJob to v1. But arena still uses v1alpha2. Can we update tfjob to v1 or v1beta2?

**Comment by cheyang** [comment]
Thank you for your suggestions! We'd like to support V1 soon. Since some of our customers are using v1alpha2, we need be careful to this. Thanks again.

**Comment by posix4e** [comment]
This broke me. posix4e@localhost:~$ arena submit tf --name=tf-dist-git                            --gpus=1                            --workers=2                            --workerImage=tensorflow/tensorflow:1.5.0-devel-gpu                --syncMode=git               --syncSource=https://github.com/cheyang/tensorflow-sample-code.git               --ps=1                            --psImage=tensorflow/tensorflow:1.5.0-devel                 --tensorboard               "python code/tensorflow-sample-code/tfjob/docker/v1alpha2/distributed-mnist/main.py --log_dir /training_logs"
Flag --workerImage has been deprecated, please use --worker-image instead
Flag --syncMode has been deprecated, please use --sync-mode instead
Flag --syncSource has been deprecated, please use --sync-source instead
Flag --psImage has been deprecated, please use --ps-image instead
ERRO[0008] Failed to execute kubectl, [create --dry-run --namespace default -f /tmp/tf-dist-git.yaml392889812] with exit status 1 
ERRO[0008] The output is service/tf-dist-git-tensorboard created (dry run)
deployment.extensions/tf-dist-git-tensorboard created (dry run)
error: unable to recognize "/tmp/tf-dist-git.yaml392889812": no matches for kind "TFJob" in version "kubeflow.org/v1alpha2"

 
exit status 1

**Comment by cheyang** [comment]
I think the workaround is that 
```
git clone https://github.com/kubeflow/arena.git
kubectl delete -f kubernetes-artifacts/tf-operator/tf-operator.yaml
kubectl create -f kubernetes-artifacts/tf-operator/tf-operator.yaml
```
By the way, what's tfjob version you are using?

**Comment by posix4e** [comment]
It totally worked , let's close it out now that it's in the FAQ. I used whatever an on kfctl gave me.

**Comment by yeya24** [comment]
Close this issue via #166
