### ISSUE TITLE
Make it easy for people to install arena

### ISSUE THREAD

**Issue by posix4e** [kubeflow/arena#164]
As a user, not wanting to do development, how do I get arena installed on my machine. Any reason why a binary or tarball is not provided?

**Comment by cheyang** [comment]
Thank you! We will provide tarball. And what OS are you using?

**Comment by posix4e** [comment]
I am on linux fedora 64. Happy to create tarballs

**Comment by cheyang** [comment]
We  have already provided the tarball to install.
