### ISSUE TITLE
Create a faq of common user problems

### ISSUE THREAD

**Issue by posix4e** [kubeflow/arena#165]
I think with such a complicated system a lot goes wrong. Maybe we create a faq to common solutions to common problems. I'm happy to do an English one if anyone agrees

**Comment by cheyang** [comment]
Thank you! Please go ahead to create a faq, and we'd like to help translate and add more Q&A.

**Comment by posix4e** [comment]
Great can we close this now? Also what do we say about pytorch support

**Comment by cheyang** [comment]
For now, we don't support pytorch yet. Please go ahead to open an issue.
