### ISSUE TITLE
[bug report] arena top job doesn't show the job which is not create by arena(created by kubectl), but arena top node shows the job

### ISSUE THREAD

**Issue by xiechengsheng** [kubeflow/arena#202]
For some training jobs that are directly created by `kubectl`, `arena top job` won't show the the gpu resources that are allocated to this job, but `arena top node` shows this info.
I think they should keep same.

**Comment by cheyang** [comment]
The purpose of `arena top node` is to help admin to check which GPU is used and which Pod is using it. And admin can clean it up to get available resources. No matter it's created by `arena`.

The purpose of `arena top job` is to manage the training Job created by `arena`. It's a concept abstraction for specific training job. I don't think all the pods can be abstracted to training job.

The different goal of the tool makes the different usage.
