### ISSUE TITLE
failed to create sparkjob

### ISSUE THREAD

**Issue by yuanbw** [kubeflow/arena#241]
Per to the guide,
https://github.com/kubeflow/arena/blob/master/docs/userguide/11-sparkjob-distributed.md
 
i submit a spark job, yet , it output the below err msg:
[root@cdh1 ~]# arena submit sparkjob --name=demo --image=registry.aliyuncs.com/acs/spark:v2.4.0 --main-class=org.apache.spark.examples.SparkPi --jar=local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar
failed to create sparkjob demo due to error Failed to find the job for demo
[root@cdh1 ~]# kubectl logs --tail=100 sparkoperator-699d5ccd6c-8g7s9   -n arena-system
I0812 06:41:44.346078       1 main.go:100] Starting the Spark Operator
I0812 06:41:44.359126       1 crd.go:48] Updating CustomResourceDefinition sparkapplications.sparkoperator.k8s.io
I0812 06:41:44.871880       1 crd.go:48] Updating CustomResourceDefinition scheduledsparkapplications.sparkoperator.k8s.io
I0812 06:41:45.381001       1 controller.go:148] Starting the workers of the SparkApplication controller
I0812 06:41:45.481271       1 controller.go:96] Starting the ScheduledSparkApplication controller
I0812 06:41:45.581495       1 controller.go:102] Starting the workers of the ScheduledSparkApplication controller

**Comment by xiechengsheng** [comment]
Hi there, this issue has been fixed in #242
