### ISSUE TITLE
Failed to submit tfjob when using helm v2.9.1

### ISSUE THREAD

**Issue by cheyang** [kubeflow/arena#289]
```
arena submit tf              --name=firstjob              --gpus=1              --annotation=s=1              --image=registry.cn-hangzhou.aliyuncs.com/tensorflow-samples/tf-mnist-standalone:gpu                   "python /app/main.py"
Error: parse error in "tfjob/templates/tfjob.yaml": template: tfjob/templates/tfjob.yaml:273: unexpected "=" in operand
Failed to execute /usr/local/bin/arena-helm, [/usr/local/bin/arena-helm template -f /tmp/values808122647 --namespace default --name firstjob /charts/tfjob > /tmp/firstjob.yaml555467658] with exit status 1
```

But when changing `usr/local/bin/arena-helm` to 2.14.1, every thing looks good.

**Comment by xiaoyili** [comment]
I'm having helm v2.9.1, but running your command returns the following error:

Error: parse error in "tfjob/templates/tfjob.yaml": template: tfjob/templates/tfjob.yaml:273: unexpected "=" in operand
Failed to execute /usr/local/bin/arena-helm, [/usr/local/bin/arena-helm template -f /tmp/values006958109 --namespace arena-system --name firstjob /charts/tfjob > /tmp/firstjob.yaml728457432] with exit status 1

**Comment by xiaoyili** [comment]
2.13.1 works as well
