### ISSUE TITLE
有计划支持pytorchjob吗？

### ISSUE THREAD

**Issue by Mddct** [kubeflow/arena#316]
pytorchjob 和tfjob在api级是一致的，有计划支持吗？

**Comment by cheyang** [comment]
目前已经支持，请试用 https://github.com/kubeflow/arena/tree/features/pytorch

**Comment by cheyang** [comment]
如果测试遇到问题，可以开issue

**Comment by cheyang** [comment]
@Mddct 请问有什么联系方式，欢迎您试用pytorch

/ping @jiaqianjing

**Comment by jiaqianjing** [comment]
您可以将您的联系方式发送邮件至 jiaqianjing@gmail.com，最好是钉钉
