### ISSUE TITLE
Speed of pytorch job

### ISSUE THREAD

**Issue by wywywy01** [kubeflow/arena#360]
Hi,  i use arena to submit pytorchjob, reference :
[（pytorch多机提交）](https://github.com/kubeflow/arena/blob/master/docs/userguide/18-pytorchjob-distributed.md)

[（pytorch单机提交）](https://github.com/kubeflow/arena/blob/master/docs/userguide/17-pytorchjob-standalone.md)

and i compare distributed and standalone style, get results blow, have you check the speed between above two mode?
![image](https://user-images.githubusercontent.com/22450352/91790932-76021280-ec44-11ea-89b4-c62a27276ba1.png)

![image](https://user-images.githubusercontent.com/22450352/91790923-6f739b00-ec44-11ea-9a25-8c3d667cc4a8.png)

Can you give me some help,  thanks sincerely!

**Comment by jiaqianjing** [comment]
分布式作业（数据并行）同时在多几个节点训练数据，单位时间内，训练的数据更多，它加速的是整个模型收敛的速度。而不是每一个 worker 的训练速度，另外，由于引入了通络通信，可能还会导致额外的开销。
分布式作业优势在于大规模训练任务

**Comment by wywywy01** [comment]
数据并行，那么每个节点训练的数据应该更少，训练的时间不应该是更少吗（考虑通信时间）？

或者说这里的例子里面，构建的dataloader并没有对数据进行拆分，这样的话每个节点还是单独跑一个训练任务，增加的时间是通信时间？

**Comment by jiaqianjing** [comment]
这个示例没有给数据进行 shard 操作，你可以看一下pytorch `torch.utils.data.DataLoader` 的 API
