### ISSUE TITLE
Custom Docker Registry images

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/arena#364]
Hello all,

So I am wondering what the sources are for the images listed below:
registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/rsync
registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/git-sync:v3.1.1
registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/jobmon
registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/kubernetes-dashboard-amd64

Are all of these just proxys for images on Docker Hub or are there special modifications made to them? If so, where are these changes documented? I am on a project that would love to use arena but I need to go over everything being run before using it.  We will need to run off a local Docker repository and would need to build all the images required ourselves for that repository.

Thanks for the help!

**Comment by happy2048** [comment]
please refer the steps to replace docker images:
1.download the images and push them to the local docker repository.
2.git clone arena source code (https://github.com/kubeflow/arena.git) 
3.use command  "grep -rn registry.cn-zhangjiakou.aliyuncs.com ./"  to search the images in the arena source code directory and replace them to your local images.
4.use command "make OS_ARCH=darwin-amd64 build-pkg" for mac or use "make OS_ARCH=linux-amd64 build-pkg" for linux
