### ISSUE TITLE
采用官方的例子 但是任务的状态一直是pending,想问下官方的例子需要使用gpu吗

### ISSUE THREAD

**Issue by lucasaytt** [kubeflow/arena#367]
![image](https://user-images.githubusercontent.com/42641861/97662700-b51cda80-1ab2-11eb-8044-b0a9d05280ff.png)

**Comment by happy2048** [comment]
文档中的例子都是使用GPU训练的。

**Comment by cheyang** [comment]
可以用arena get {job-name} -d看一下pending原因

**Comment by lucasaytt** [comment]
找到问题 谢谢
