### ISSUE TITLE
无法获取日志，invalid instance name

### ISSUE THREAD

**Issue by lppsuixn** [kubeflow/arena#496]
![image](https://user-images.githubusercontent.com/12748339/110796911-73e3d500-82b3-11eb-80c0-a704aa34d9a1.png)
k8s 版本: v16.3
arena 版本: v0.7.0+3559f56
现象:
arena get job 正常
arena log job 报错:ERRO[0000] training job not found,please use 'arena list' to make sure job is existed.

**Comment by happy2048** [comment]
please use command: arena logs lpp -i lpp-chief-0，the option '-i' is used to specify the instance name.
