### ISSUE TITLE
`clean-task-policy`  support `All` when submitting tfjobs

### ISSUE THREAD

**Issue by 1202zhyl** [kubeflow/arena#536]
arena should support clean-task-policy "All"  when training via tfjobs.
currently, only supports "Running"(clean RUNNING pod) or None(do nothing).
when job is done, often we need to remove ps, chief, evaluator and worker.

**Comment by cheyang** [comment]
@1202zhyl would you like to contribute?

**Comment by hzliangbin** [comment]
@cheyang I'm just using kubeflow recently and quite interested in this issue. may I take it ?
