### ISSUE TITLE
helm 3+ support

### ISSUE THREAD

**Issue by tzstoyanov** [kubeflow/arena#736]
I have problems running arena with the latest helm v3.5.2:
`Error: unknown flag: --name`
`ERRO[0000] Failed to execute /usr/local/bin/arena-helm, [/usr/local/bin/arena-helm template -f /tmp/values002311273 --namespace default --name tf-standalone-test-with-git /charts/tfjob > /tmp/tf-standalone-test-with-git.yaml729397940] with exit status 1 `

I have helm installed on my system and just did a symlink to `arena-helm`:
`arena-helm version`
`version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

Looks like `--name` parameter is deprecated in helm v3, the syntax is different.

Are there any plans to support the latest helm ?

**Comment by happy2048** [comment]
do it in the next month

**Comment by happy2048** [comment]
helm has been upgraded to v3
