### ISSUE TITLE
Rotate secrets stored in CircleCI

### ISSUE THREAD

**Issue by eliaslevy** [kubeflow/arena#896]
CircleCI [suffered](https://circleci.com/blog/jan-4-2023-incident-report/) a breach. Any secrets stored in CircleCI have potentially leaked. There is evidence the attackers have used leaked credentials against some CircleCI user. Any secrets stored in CircleCI should be invalidated. It appears this repo is using an SSH key to allow checkouts from CircleCI. The key should be rotated.

**Comment by gkcalat** [comment]
Hi @cheyang!
It seems that the repo uses CircleCI: https://github.com/kubeflow/arena/blob/master/.circleci/config.yml

Do you have the account credentials from CircleCI? Due to the breach describe above by @eliaslevy, we need the secrets to be regenerated.

**Comment by gkcalat** [comment]
@gaocegege, can you take a look on this or help reaching out to the repo owners?

**Comment by cheyang** [comment]
@gkcalat thank you. We've deleted CircleCI dependency.
